### ISSUE TITLE
Error using Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [syohex/emacs-go-direx#4]
your package can't be install using only Melpa stable : 

```bash
Dependency go-direx failed to install: Package `direx-0.1alpha' is unavailable
```

I creates an issue for the *direx* package [1].

[1] : https://github.com/m2ym/direx-el/issues/42

**Comment by syohex** [comment]
Thanks for reporting.

direx-el tagged v1.0.0. So I have updated dependency version of it.
Please try again.
